/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as RecuperarSenhaRouteImport } from './app/routes/recuperar-senha'
import { Route as authenticatedRouteRouteImport } from './app/routes/(authenticated)/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as authenticatedPerfilIndexRouteImport } from './app/routes/(authenticated)/perfil/index'
import { Route as authenticatedNotificacoesIndexRouteImport } from './app/routes/(authenticated)/notificacoes/index'
import { Route as authenticatedEmpresasIndexRouteImport } from './app/routes/(authenticated)/empresas/index'
import { Route as authenticatedEmpresasCompanySlugIndexRouteImport } from './app/routes/(authenticated)/empresas/$company-slug/index'
import { Route as authenticatedEmpresasCompanySlugDocumentosIndexRouteImport } from './app/routes/(authenticated)/empresas/$company-slug/documentos/index'
import { Route as authenticatedEmpresasCompanySlugDocumentosDocumentIdRouteImport } from './app/routes/(authenticated)/empresas/$company-slug/documentos/$documentId'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedPerfilIndexRoute =
  authenticatedPerfilIndexRouteImport.update({
    id: '/perfil/',
    path: '/perfil/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedNotificacoesIndexRoute =
  authenticatedNotificacoesIndexRouteImport.update({
    id: '/notificacoes/',
    path: '/notificacoes/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedEmpresasIndexRoute =
  authenticatedEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedEmpresasCompanySlugIndexRoute =
  authenticatedEmpresasCompanySlugIndexRouteImport.update({
    id: '/empresas/$company-slug/',
    path: '/empresas/$company-slug/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedEmpresasCompanySlugDocumentosIndexRoute =
  authenticatedEmpresasCompanySlugDocumentosIndexRouteImport.update({
    id: '/empresas/$company-slug/documentos/',
    path: '/empresas/$company-slug/documentos/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute =
  authenticatedEmpresasCompanySlugDocumentosDocumentIdRouteImport.update({
    id: '/empresas/$company-slug/documentos/$documentId',
    path: '/empresas/$company-slug/documentos/$documentId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedRouteRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/empresas': typeof authenticatedEmpresasIndexRoute
  '/notificacoes': typeof authenticatedNotificacoesIndexRoute
  '/perfil': typeof authenticatedPerfilIndexRoute
  '/empresas/$company-slug': typeof authenticatedEmpresasCompanySlugIndexRoute
  '/empresas/$company-slug/documentos/$documentId': typeof authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute
  '/empresas/$company-slug/documentos': typeof authenticatedEmpresasCompanySlugDocumentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedRouteRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/empresas': typeof authenticatedEmpresasIndexRoute
  '/notificacoes': typeof authenticatedNotificacoesIndexRoute
  '/perfil': typeof authenticatedPerfilIndexRoute
  '/empresas/$company-slug': typeof authenticatedEmpresasCompanySlugIndexRoute
  '/empresas/$company-slug/documentos/$documentId': typeof authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute
  '/empresas/$company-slug/documentos': typeof authenticatedEmpresasCompanySlugDocumentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/(authenticated)/empresas/': typeof authenticatedEmpresasIndexRoute
  '/(authenticated)/notificacoes/': typeof authenticatedNotificacoesIndexRoute
  '/(authenticated)/perfil/': typeof authenticatedPerfilIndexRoute
  '/(authenticated)/empresas/$company-slug/': typeof authenticatedEmpresasCompanySlugIndexRoute
  '/(authenticated)/empresas/$company-slug/documentos/$documentId': typeof authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute
  '/(authenticated)/empresas/$company-slug/documentos/': typeof authenticatedEmpresasCompanySlugDocumentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recuperar-senha'
    | '/empresas'
    | '/notificacoes'
    | '/perfil'
    | '/empresas/$company-slug'
    | '/empresas/$company-slug/documentos/$documentId'
    | '/empresas/$company-slug/documentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recuperar-senha'
    | '/empresas'
    | '/notificacoes'
    | '/perfil'
    | '/empresas/$company-slug'
    | '/empresas/$company-slug/documentos/$documentId'
    | '/empresas/$company-slug/documentos'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/recuperar-senha'
    | '/(authenticated)/empresas/'
    | '/(authenticated)/notificacoes/'
    | '/(authenticated)/perfil/'
    | '/(authenticated)/empresas/$company-slug/'
    | '/(authenticated)/empresas/$company-slug/documentos/$documentId'
    | '/(authenticated)/empresas/$company-slug/documentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/perfil/': {
      id: '/(authenticated)/perfil/'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof authenticatedPerfilIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/notificacoes/': {
      id: '/(authenticated)/notificacoes/'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof authenticatedNotificacoesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/empresas/': {
      id: '/(authenticated)/empresas/'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof authenticatedEmpresasIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/empresas/$company-slug/': {
      id: '/(authenticated)/empresas/$company-slug/'
      path: '/empresas/$company-slug'
      fullPath: '/empresas/$company-slug'
      preLoaderRoute: typeof authenticatedEmpresasCompanySlugIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/empresas/$company-slug/documentos/': {
      id: '/(authenticated)/empresas/$company-slug/documentos/'
      path: '/empresas/$company-slug/documentos'
      fullPath: '/empresas/$company-slug/documentos'
      preLoaderRoute: typeof authenticatedEmpresasCompanySlugDocumentosIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/empresas/$company-slug/documentos/$documentId': {
      id: '/(authenticated)/empresas/$company-slug/documentos/$documentId'
      path: '/empresas/$company-slug/documentos/$documentId'
      fullPath: '/empresas/$company-slug/documentos/$documentId'
      preLoaderRoute: typeof authenticatedEmpresasCompanySlugDocumentosDocumentIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedEmpresasIndexRoute: typeof authenticatedEmpresasIndexRoute
  authenticatedNotificacoesIndexRoute: typeof authenticatedNotificacoesIndexRoute
  authenticatedPerfilIndexRoute: typeof authenticatedPerfilIndexRoute
  authenticatedEmpresasCompanySlugIndexRoute: typeof authenticatedEmpresasCompanySlugIndexRoute
  authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute: typeof authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute
  authenticatedEmpresasCompanySlugDocumentosIndexRoute: typeof authenticatedEmpresasCompanySlugDocumentosIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedEmpresasIndexRoute: authenticatedEmpresasIndexRoute,
  authenticatedNotificacoesIndexRoute: authenticatedNotificacoesIndexRoute,
  authenticatedPerfilIndexRoute: authenticatedPerfilIndexRoute,
  authenticatedEmpresasCompanySlugIndexRoute:
    authenticatedEmpresasCompanySlugIndexRoute,
  authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute:
    authenticatedEmpresasCompanySlugDocumentosDocumentIdRoute,
  authenticatedEmpresasCompanySlugDocumentosIndexRoute:
    authenticatedEmpresasCompanySlugDocumentosIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
